language: csharp
solution: Sitecore.Flow.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - mono .nuget/nuget.exe restore Sitecore.Flow.sln -Verbosity detailed
script: 
  - xbuild /p:Configuration=Release Sitecore.Flow.sln